theme: jekyll-theme-minimal

# --- Required options --- #

# Name and description
title: Umut Durak
description: Research Scientist, Group Leader, Coordinator, Professor, Husband, Father.

# My pictirer
logo: /assets/img/umut.jpeg